apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: storageclass
  name: managed-nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: fuseim.pri/ifs
parameters:
  archiveOnDelete: "false"
